---
title: "Arsenic levels in drinking water"
description: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### About this project:

Maine and New Hampshire have among the highest per capita reliance on private wells for drinking water in the United States (ME: 56% and NH: 40%). Approximately 10% of Maine wells and 20% of New Hampshire wells have elevated levels of arsenic, yet well water testing rates are low in both states.

In August 2018, MDI Biological Laboratory received a 5-year NIH-NIGMS Science Education Partnership Award (SEPA) to create and pilot a national model of STEM (Science, Technology, Engineering, and Math) education. The project, "Data to Action: A Secondary School-Based Citizen Science Project to Address Arsenic Contamination of Well Water" engages students as citizen scientists and provides them with the tools and skills to make sense of data so that their results can lead to change in their communities. This work will also help the region better understand the cycle of arsenic on agricultural land and in home gardens, and its potential effects on human health, from exposure such as eating produce, touching soil, or breathing in soil dust. You can read more about this project at this recent [MDIBL blog post](https://mdibl.org/funding-helps-expand-arsenic-awareness-program/) .

**Maximum Contaminant Levels:** The numbers below are federal standards set by the EPA for the maximum contaminant amount allowed in drinking water. These are set to protect public health. There are a few exceptions to the Maximum Contaminant Levels.

-   Beryllium: 4 ug/L
-   Chromium: 100 ug/L
-   Manganese: 50 ug/L\*\*
-   Iron: 300 ug/L\*\*
-   Nickel: N/A
-   Copper: 1300 ug/L\*
-   Arsenic: 10 ug/L; New Hampshire lowered their MCL to 5 ug/L in 2019.
-   Selenium: 50 ug/L
-   Cadmium: 5 ug/L
-   Antimony: 6 ug/L
-   Barium: 2000 ug/L
-   Thallium: 2 ug/L
-   Lead: 15 ug/L
-   Uranium: 30 ug/L

\*Lead and Copper are regulated under an action level because they enter drinking water primarily through plumbing materials. Treatment at the tap is recommended.

\*\*Iron and Manganese are "secondary standards" and not health threatening. The EPA sets these standards because contaminants present in your water above these standards may cause your water to be discolored, taste odd, or have an odor. However, your water is still safe to drink

